id = "daleth"
name = "daleth"
description = "daleth support."
version = "0.1.0"
schema_version = 1
authors = ["Artemy Egorov <me@artegoser.ru>"]
repository = "https://github.com/TxtDot/daleth-zed"

[grammars.daleth]
repository = "https://github.com/TxtDot/tree-sitter-daleth"
commit = "4d3207c80dcef793db7c9bc700f8265eb707c9ad"
